config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users

  get 'autocomplete/:topic', to: 'autocomplete#show'

  resources :products

  get 'positions/list/:slug', to: 'positions#list'
  resources :positions
  resources :orders
  resources :users

  get  '/baskets/:order_id', to: 'baskets#show'
  post '/baskets/add', to: 'baskets#create'
  post '/baskets/remove', to: 'baskets#destroy'
  put  '/baskets/:id', to: 'baskets#update'

  get  '/locations/:slug', to: 'locations#show'
  post '/locations', to: 'locations#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labofill</title>
    <meta name="description" content="Gestion d'un stock FTW">
    <%= csrf_meta_tags %>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' name='viewport'>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <script type='text/javascript'>
      currentUser = {
        id: <%= @current_user.id %>,
        first_name: "<%= @current_user.first_name %>",
        last_name: "<%= @current_user.last_name %>"
      };
      const messages = {
        en: {
          message: {
            hello: 'hello world'
          }
        }
      };
    </script>

    <div id='app'>
      <router-view></router-view>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cedric</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'application', media: 'all' %>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' name='viewport'>
  </head>

  <body>
    <div class='container'>
      <div class='row' style='padding: 10px;'>
        <div class='col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-md-offset-4'>
          <h2>Gestion du stock</h2>

          <% if flash.any? %>
            <ul>
            <% flash.each do |key, value| %>
               <li style='color: red'><%= value %></li>
            <% end %>
            <br />
            </ul>
          <% end %>

          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true %>
            </div>

            <div class="field">
              <%= f.label :password %><br />
              <%= f.password_field :password, autocomplete: "off" %>
            </div>

            <% if devise_mapping.rememberable? -%>
              <div class="field">
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me %>
              </div>
            <% end -%>

            <div class="actions">
              <%= f.submit "Log in", class: 'btn btn-danger btn-block' %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </body>
</html>